### ISSUE TITLE
Enable (KVM) Kernel-based Virtual Machine

### ISSUE THREAD

**Issue by ghost** [mvaisakh/kernel_xiaomi_cannon#1]

**Comment by mvaisakh** [comment]
Enabled required configs in 
https://github.com/mvaisakh/kernel_xiaomi_cannon/commit/748e3ad2537a8d0ac6f658281ae7f543dc8a6028 and https://github.com/mvaisakh/kernel_xiaomi_cannon/commit/24e3cc25671b65af4cc1c8f42938a02262e93203
