### ISSUE TITLE
Excuse me.Does it support android 11?

### ISSUE THREAD

**Issue by chen2021-web** [mvaisakh/kernel_xiaomi_cannon#2]

**Comment by chen2021-web** [comment]
My device is cannon

**Comment by mvaisakh** [comment]
Yes, it supports Android 11, but there are a few issues on it. I'd recommend not to use it for now. I shall close this issue when the kernel is stable.

**Comment by mvaisakh** [comment]
Android 11 and Android support has been added. Please use Eva Kernel Release 4.
https://github.com/mvaisakh/kernel_xiaomi_cannon/releases/tag/v4
