### ISSUE TITLE
Front facing camera doesn't work with this kernel

### ISSUE THREAD

**Issue by chaoscreater** [mvaisakh/kernel_xiaomi_cannon#3]
I'm on stock MIUI 12.5.5 Android 11.

When using front facing camera, it lags extremely bad. This happens in both the Face Unlock setting (which uses front facing camera), as well as the MIUI Camera app. This wasn't an issue with stock kernel.

Back camera is fine.

UPDATE:

I just flashed my stock boot.img and vbmeta.img back and now all my issues described above are gone. No more "there's an internal problem with your device" error and front facing camera working again. Your kernel is not stable, it's causing these issues....

**Comment by mvaisakh** [comment]
All of these issues have been resolved. Please use Eva Kernel Release 4

https://github.com/mvaisakh/kernel_xiaomi_cannon/releases/tag/v4
