### ISSUE TITLE
There's an internal problem with your device. Contact your manfufacturer for details

### ISSUE THREAD

**Issue by chaoscreater** [mvaisakh/kernel_xiaomi_cannon#4]
I'm using stock MIUI 12.5.5. I flashed TWRP + vbmeta and flashed your v3 kernel.

I'm getting this error everytime on startup - "Android System There's an internal problem with your device. Contact your manfufacturer for details".

I Googled this a bit and it seems to be related to Magisk. I'm not using Magisk, I just want to keep my phone unrooted for now. When flashing the kernel, it mentioned something to do with creating kernel helper Magisk module.

Does this kernel need an update to make it work 100% on non-rooted stock MIUI? 

UPDATE:

I just flashed my stock boot.img and vbmeta.img back and now all my issues described above are gone. No more "there's an internal problem with your device" error and front facing camera working again. Your kernel is not stable, it's causing these issues....

**Comment by mvaisakh** [comment]
All of these issues have been resolved, please use Eva Kernel Release 4.

https://github.com/mvaisakh/kernel_xiaomi_cannon/releases/tag/v4
