### ISSUE TITLE
Some apps crash

### ISSUE THREAD

**Issue by KondratokGK** [mvaisakh/kernel_xiaomi_cannon#6]
I use crDroid 7.13. When i use Eva Kernel 3 no bug. If i use Eva Kernel 4 some apps like keyboard or spotify will crash after a few days of smartphone usage.

**Comment by mvaisakh** [comment]
Can you attach a log when the apps crash?

Use commands:
`adb logcat > logs.log`
`adb shell dmesg > dmesg.log`

And send both files.

**Comment by KondratokGK** [comment]
[logs.log](https://github.com/mvaisakh/kernel_xiaomi_cannon/files/7966392/logs.log)
[dmesg.log](https://github.com/mvaisakh/kernel_xiaomi_cannon/files/7966399/dmesg.log)

**Comment by mvaisakh** [comment]
This issue should be fixed with Release 5, please try and let me know
